### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by danraymond** [Quorafind/Obsidian-Surfing#100]
### Feature Requested

Screenshot when you have opened web page inside Obsidian. I use a lot of mapping software and much of it is url based. So I ma already able to open it in Obsidian using Surfer (fantastic this is!!!).

I would love to be able to screenshot to an image in Obsidian. I do this now using Greenshot externally and saving into the  Obsidian tree.

Would be delightful to be able to say right click and save a screenshot directly!

Thank you

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
I will try to do it, but no gurrantee

**Comment by Quorafind** [comment]
I found that it was possible to capture screenshot from current viewport, and it is not possible to capture whole page's screenshot, If it is enough?

**Comment by danraymond** [comment]
That would be awesome! I know catching whole web page problematic as i am
also a programmer.

Thank you so much.

Dan

**Comment by Quorafind** [comment]
Available when #113 is merged
