### ISSUE TITLE
Forward-backward mouse button support + reload/dupplicate item in tab right click menu

### ISSUE THREAD

**Issue by vguillet** [Quorafind/Obsidian-Surfing#101]
### Feature Requested

The title says it all, I am very accustomed to forward-backward side button navigation, and would love to have it in surf. Furthermore adding the common refresh/duplicate items in the tab right-click menu would also help match common browser behavior. 

Lastly, having the ability to open in a new tab the previous/next page by scroll wheel (middle mouse) clicking the previous/next arrows would also be great to have!

Cheers and thanks for the great work, using the plugin virtually all the time nowadays!

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
I need some time to figure out how to recognize forward-backward side button navigation when in surfing itself. Could you add Obsidian commands to them?

**Comment by agnoldo** [comment]
Hello, congratulations again to @Quorafind and his amazing work.

As I commented in https://github.com/Quorafind/Obsidian-Surfing/issues/106#issuecomment-1367696583, it's possible to add a button Refresh to the Surfing toolbar. In addition, the latest version as of today (0.6.7) contains Back-Forward buttons on the left of the toolbar.

Best regards!

**Comment by Quorafind** [comment]
Available when #113 is merged.
