### ISSUE TITLE
Feature Request: Add refresh button

### ISSUE THREAD

**Issue by pcause** [Quorafind/Obsidian-Surfing#106]
### Feature Requested

Love this addin.  Ccan you add a refresh button next to the forward/back arrows

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Will be an option in next version.

**Comment by agnoldo** [comment]
Hello, congratulations and thanks to @Quorafind for the amazing work! I always wanted to have a proper web browser inside Obsidian.

I was able to have the same behavior by adding a button connected to the action "Surfing: Refresh Current Page" to the toolbar of the Surfing browser tab. To do that, simply hover on the toolbar right to the URL field and a + button will show up. Click it and select this action and an icon. It worked beautifully.

BTW, I would love to see more commands available there.

**Comment by Quorafind** [comment]
@pcause Thanks~I will add more commands for better user experience.

**Comment by Quorafind** [comment]
DONE
