### ISSUE TITLE
[Bug]:  Bookmarks broken

### ISSUE THREAD

**Issue by pcause** [Quorafind/Obsidian-Surfing#107]
### Bug Description

I enable bookmarks and then try to delete a bookmark, they don't delete.

### To Reproduce

- install plugin and exit and reload obsidian
- create a page with web link
- open the web link in obsidian (new tab is default)
- exit and reload
- - in the open web page click the setting icon and enable bookmarks, close settings
-  there is no bookmarks icon in left sidebar, so exit and reload
- - click the bookmarks icon in left sidebar
- click delete on the first item and then second item
- first is not gone.  page won't scroll, etc.  bookmarks seem broken
I do have custom frames installed but disabled.

### Obsidian Version

1.1.9

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Will be fixed in next version.

**Comment by pcause** [comment]
loaded 0.70 still broken:

- first, you have to restart after enabling bookmarks.  and if you have old bookmarks there you need to delete it.
- once I restart I can open and get a blank bookmarks page.  I can add an item but if I close bookmarks and reopen, not there.
- clicking on the bookmark (just added, didn't close) opens in browser.  no way to open in obsidian.  right click but no menu

**Comment by Quorafind** [comment]
😂 I forgot this . Sorry, added to my todo list

**Comment by Quorafind** [comment]
Fixed via #113

**Comment by likemuuxi** [comment]
Bug 描述
书签管理器无法打开，存在时间已久，之前在管理器无法删除书签，一次性在设置中把所有书签删掉导致

相关截图
![image](https://user-images.githubusercontent.com/85612715/230902623-e3b2064a-160d-4ebb-b842-b20582aa04d0.png)

相关尝试
手动安装、更新插件、升级Obsidian，退出并重新加载Obsidian均无用。

Obsidian 版本
1.1.16

只安装了Surfing，Custom Frames已移除
插件版本0.8.16

**Comment by oscaromsn** [comment]
i can't remove bookmarks too
