### ISSUE TITLE
Current Search Bar Hotkey

### ISSUE THREAD

**Issue by conneroisu** [Quorafind/Obsidian-Surfing#112]
### Feature Requested

A command through surfing can be used to edit the current search bar using a command slash hotkey. Editing the search bar is done often and should be as quick and easy as possible.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
press `/` why you are in surfing view.

**Comment by Quorafind** [comment]
Oh, you mean specific hotkey.

**Comment by Quorafind** [comment]
Done, will be available while pr is merged

**Comment by conneroisu** [comment]
Thanks! That was so quick! Nice work! Do you plan on expanding t?
