### ISSUE TITLE
[Bug]: macOS没有复制指向突出显示的链接的格式功能

### ISSUE THREAD

**Issue by penglanm** [Quorafind/Obsidian-Surfing#116]
### Bug Description

系统版本：macos Ventura 13.1
Surfing版本：0.7.0
问题：
1. 右键没有复制高亮选项，只有复制选项
2. 文字复制进md文件中没有链接跳转功能

<img width="793" alt="image" src="https://user-images.githubusercontent.com/26063641/210166660-4675feb6-3a06-418c-8941-db158314ba9e.png">

### Relevant Screenshot

<img width="774" alt="image" src="https://user-images.githubusercontent.com/26063641/210166701-de038f9f-bf5d-4916-9931-98cd73431f81.png">

### To Reproduce

右键没有复制高亮选项，只有复制选项

### Obsidian Version

1.1.9

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
不知道怎么修复，而且测试过认为是上游bug

**Comment by Quorafind** [comment]
现在你可以尝试用提供的命令来快速复制

**Comment by penglanm** [comment]
> 

请问“提供的命令”是指哪里提供的命令啊？

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/210715236-add8c3e2-f36f-4dea-abff-c719e90a791b.png)

**Comment by penglanm** [comment]
> ![image](https://user-images.githubusercontent.com/13215013/210715236-add8c3e2-f36f-4dea-abff-c719e90a791b.png)

成功了，感谢

**Comment by CatsOfMrXue** [comment]
@Quorafind 你好，我按照上面的步骤配置了快捷键，选中文本之后跳出了下面这个图片，请问可能是什么问题?插件版本0.8.16，Macos Ventura 13.2.1
<img width="797" alt="image" src="https://user-images.githubusercontent.com/46380455/232057091-e6a67d61-549a-403d-a5f6-91b7bdbece16.png">
