### ISSUE TITLE
[Bug]: Selecting a tab reloads itself, after relaunch of obsidian app

### ISSUE THREAD

**Issue by profucius** [Quorafind/Obsidian-Surfing#117]
### Bug Description

Tabs from a previous Obsidian instance, after a close and relaunch of the application, will cause itself to reload when activated back from another tab in the same pane.

## 1 On a fresh start of Obsidian, the open Surfing tabs from a previous instance will continue reloading themselves each time they are re-activated from another tab.
![num1](https://user-images.githubusercontent.com/18254607/210302246-c7c8b4f9-6895-47bb-955e-dc6d7e4fbc00.gif)

## 2 If new tabs are opened, they work fine. Until Obsidian is quit and relaunched. these will not reload continuously.
[Imgur GIF](https://imgur.com/a/EhR5oW8) (uploaded to imgur, as inserting them all into this ticket would have been chaos)

## 3 Can also copy/pasted the URLs of the "bad tabs" into new tabs, and these will no longer reload themselves. It does not matter if the bad tabs are closed or not.
[Imgur GIF](https://imgur.com/a/onEdEtc)

## 4 Demonstrating that the issue persists even when Surfing is the only plugin enabled in all of Obsidian.
[Imgur GIF](https://imgur.com/a/v2XrHwG)

### To Reproduce

1. Open a tab and go to a Todoist.com or Notion.so page or subpage.
2. Notice it works as intended, when you go to another tab in that same pane, and back, the page remains loaded.
3. Quit Obsidian application.
4. Launch Obsidian. Go to the Surfing tab of Todoist/Notion.
5. Go to the other tab open in that same pane, then go back to the tab of Todoist/Notion.
6. Notice that the tab reloads itself. Repeat step 5, the tab will reload again every time.
7. Copy the URL to that Todoist/Notion page. Close that tab.
8. In a new tab in that same pane (or any other pane) paste that URL and go to it.
9. Repeat steps 2-5. Notice the issue repeats.

### Obsidian Version

1.1.9

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Will be fixed in next / next x2 version.

**Comment by profucius** [comment]
> Will be fixed in next / next x2 version.

Wonderful. Can you speculate as to how far away that is?  I reload Obsidian often, so this is a pain point for me at the moment. Thanks

**Comment by Quorafind** [comment]
Fixed via #113

**Comment by profucius** [comment]
Much of that is in non-English so I cannot understand it. But it seems like progress so that is good.

If you would like a beta-tester for the newest version, I am happy to help. Let me know if you'd like me to test. Thanks
