### ISSUE TITLE
[Bug]: Bookmark button almost eniterly covered up

### ISSUE THREAD

**Issue by j-maffe** [Quorafind/Obsidian-Surfing#120]
### Bug Description

I've noticed that the bookmark button on the top-right of the screen is almost entirely covered up in the New tab view (with the search on a new tab turned off). It is half covered up when browsing websites. I'm using the Minimal Theme if that's relevant. Awesome work on the plugin!!
![image](https://user-images.githubusercontent.com/120587170/210553453-fb49000d-bf43-4e34-8d81-598e02d3b883.png)
![image](https://user-images.githubusercontent.com/120587170/210553478-23134058-13b8-41da-a817-95a415434287.png)

### Obsidian Version

1.1.9

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
fixed.
