### ISSUE TITLE
[Bug]: ob外链无法跳转打开

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Obsidian-Surfing#125]
### Bug Description

直接点击链接, 比如`https://github.com/Quorafind/Obsidian-Surfing/issues`, 能够正常跳转打开.
但是对于`[link name](https://github.com/Quorafind/Obsidian-Surfing/issues)`, 无法正常跳转打开. 任何链接都是这样.
不确定是不是我个人的问题, 感觉上忽然就不好使了.

### Obsidian Version

1.1.9

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
无法复现，我在沙箱库中也能正常跳转，你可以按 Ctrl+Shift+i 看一下控制台有没有任何报错，如果没有的话，建议重启一次 Obsidian 

https://user-images.githubusercontent.com/13215013/210705231-aa5d309e-c0d8-42cb-8855-c5ff70a443b2.mp4

**Comment by Quorafind** [comment]
如果还有问题的话，请重新开 issue

**Comment by XMB-7** [comment]
确实, 我用沙箱试了一下也没问题. 然后我当前库的报错信息如下.
![image](https://user-images.githubusercontent.com/65625632/210716449-4895a7e4-6abc-480b-9162-544cb51ca915.png)

**Comment by Quorafind** [comment]
貌似是因为 HTML 被抢占了，你有安装别的  HTML 阅读器吗？不过这个应该不会影响正常功能，你可以试着重装一次 surfing

**Comment by XMB-7** [comment]
重装之后确实没再报错, 亦即跟HTML没关系.
然后我发现问题了, 因为我用了以下css, 然后习惯点击图标进行跳转. 现在是点这个图标无响应, 然后取消该css直接点击链接本体则正常.
```
.cm-link .cm-underline {
    pointer-events: none;  /* 点击外链直接修改外链名字 点击图标才会跳转 */
}
```
![image](https://user-images.githubusercontent.com/65625632/210719152-e1672599-3890-4a55-a272-2b549939e3e6.png)

**Comment by XMB-7** [comment]
之前的版本是支持点击图标进行跳转的, 可能是做了什么改动使之失效了, 所以给我感觉是突然就不好使了. 如果能排查下就再好不过了.

**Comment by Quorafind** [comment]
我这边已经修复，应该是新增的某些代码导致的
