### ISSUE TITLE
请问书签的分类如何设置？

### ISSUE THREAD

**Issue by wuzhen97** [Quorafind/Obsidian-Surfing#126]
### Bug Description

请问书签的分类如何设置？我尝试设置如下，但没有效果：

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/61906420/210710260-af34f05e-13b5-44ce-b27f-e473cae20dc5.png)
![image](https://user-images.githubusercontent.com/61906420/210710306-dcfd334c-e0e4-45e4-a4ee-3f7c00e07e0c.png)

### To Reproduce

设置完分类后，重启、刷新都尝试过。在书签管理器的分类选项中仅有ROOT

### Obsidian Version

1.1.9

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
```markdown
- 目录1
    - 目录2
    - 目录3
```

用列表形式缩进表示

**Comment by Quorafind** [comment]
刚刚推送了更新，你删除所有内容后会自动显示

**Comment by wuzhen97** [comment]
> ```gfm
> - 目录1
>     - 目录2
>     - 目录3
> ```
> 
> 用列表形式缩进表示

谢谢~
