### ISSUE TITLE
Feature Request: Option to *not* automatically open external links inside Obsidian

### ISSUE THREAD

**Issue by chrisgrieser** [Quorafind/Obsidian-Surfing#132]
### Feature Requested

With the plugin installed, every link I click will be opened in an Obsidian tab. While having an option to do so is useful, I find it quite annoying that it *always* happens. 

If there is a link in a note that I want to open in the browser, I have two options.
Option one:
- click on the link
- wait for the site to load
- right click
- select "Open URL in External browser"
- wait *again* for the link to load
- and when I am going back to Obsidian, I also have a leftover tab which I now need to close

Option two:
- right click the link
- copy the url
- alt+tab multiple times until I am in the browser
- go to the address bar
- paste the link there
- press return
- wait for the site to load

Especially when you work with a lot of links, this is very, very tedious compared to the default "click on the link and you are in browser".

Would it be possible to have an option to *disable* the Surfing plugin's behavior of always opening every URL in Obsidian, and add a command or right-click-menu-item to open the link inside Obsidian?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
You can hold metakey and click to open it in external browser

**Comment by chrisgrieser** [comment]
Shears tried all modifier keys, does not work

**Comment by Quorafind** [comment]
Weird, i will check it again and then nake an option that allows you open external or in obsidian by default.

**Comment by Quorafind** [comment]
@chrisgrieser can you check again if the issue remains when you are holding metakey? btw, I file a new fr issue #135

**Comment by chrisgrieser** [comment]
it does, but I discovered that on mac, it seems to be the `cmd` key instead, so command+click opens in the external browser.

**Comment by MochaMoth** [comment]
I am having this issue in Linux. I would like https links to continue opening in Chrome, not inside a firefox tab within obsidian. This only started happening after updating to this latest version.

**Comment by eKerney** [comment]
Has this been resolved?  On Windows 11 hotkey to open in external browser does not work.
Thank you, great plugin!

**Comment by W1Real** [comment]
On windows 10 `CTRL` + Click.
