### ISSUE TITLE
[Bug]: 页面显示范围超出

### ISSUE THREAD

**Issue by Jewel-bin** [Quorafind/Obsidian-Surfing#136]
### Bug Description

1. 页面超出tab显示范围（默认外观、未启用css片段时同样超出）
2. 缩小后作为独立导航组件时的界面布局问题（或许算是一个request, 空白页好像不太适合用作实现这样的功能...不过自适应搜索框感觉还是可以有的🙌）

### Relevant Screenshot

![屏幕截图 2023-01-09](https://user-images.githubusercontent.com/69795384/211350694-72c5404c-15f1-4a5f-bf41-93031a03da8e.png)

### Obsidian Version

v1.1.9

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
我在 style 里面用了 :has 来解决这个问题，不过不适用于旧安装版本的ob，后续我再向前兼容一下
