### ISSUE TITLE
Feature Request: Drag and drop from a pdf opened in the browser

### ISSUE THREAD

**Issue by 1chevre** [Quorafind/Obsidian-Surfing#141]
### Feature Requested

Hey!

I love the fact than you can drag and drop text directly from a webpage into a canvas or a note with your plugin.
I wish I could do the same with a pdf opened into the browser, is this something that is feasible?

Thanks

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
It is impossible now for this plugin, surfing doesnt handle pdf files.
