### ISSUE TITLE
[Bug]: 通过快捷键调用复制指向突出链接功能, 总是报错.

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Obsidian-Surfing#142]
### Bug Description

不用快捷键能正常复制链接, 但用了快捷键, 对不同网页会自动弹出不同的报错信息.

![image](https://user-images.githubusercontent.com/65625632/212226539-815c8225-8227-4a5f-926d-ed90f005168b.png)

![image](https://user-images.githubusercontent.com/65625632/212226612-82539a6e-fabb-4f10-b766-983cbbe10bca.png)

![image](https://user-images.githubusercontent.com/65625632/212226934-b73b03a3-28c3-4827-98f9-61d46de942e5.png)

### Obsidian Version

1.1.9

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
因为功能被屏蔽了

**Comment by XMB-7** [comment]
呃, 是插件暂时屏蔽了这个功能么, 还是我这边有什么误操作把它给屏蔽了? 我这边应该是什么也没做, 插件设置里也没有关闭该功能的选项...
