### ISSUE TITLE
Feature Request: Stop reloading when tab pane is moving one side to other

### ISSUE THREAD

**Issue by echo-saurav** [Quorafind/Obsidian-Surfing#147]
### Feature Requested

I am kinda suspecting obsidian itself reload the pane when tab move around,  but it would be great if it don't reload when we move tab

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
I don't think it is possible because Obsidian handles the leaf's life time behavior. If Obsidian dev doesn't update its default behavior, this issue would be closed by default.
