### ISSUE TITLE
[Bug]: 显示不完全

### ISSUE THREAD

**Issue by jisidehuli** [Quorafind/Obsidian-Surfing#151]
### Bug Description

如图，只能在页面的上部分显示网页，无法完全填充页面

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/39455147/216798955-74d1d804-b1cf-4b84-b5cc-6dfcf3cc26b4.png)
![image](https://user-images.githubusercontent.com/39455147/216798966-7688ad66-0224-4038-8f50-ce160c40b6cc.png)

### Obsidian Version

1.1.9

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
检查默认主题是否有一样的情况

**Comment by jisidehuli** [comment]
> 检查默认主题是否有一样的情况

![image](https://user-images.githubusercontent.com/39455147/216804658-e8823733-b1dc-4ce6-be01-1534e304e4a9.png)
默认主题应该是正常的，只有surfing不太能使用，感觉有点奇怪

![image](https://user-images.githubusercontent.com/39455147/216804682-c8a6f9d3-ad7e-4ce2-8e8b-a97bfa64898a.png)
![image](https://user-images.githubusercontent.com/39455147/216804686-ff8ed190-9549-4802-9087-3abe9f141629.png)

**Comment by jisidehuli** [comment]
> 检查默认主题是否有一样的情况
发现问题了大佬，从插件库里直接安装的话，好像没有css文件，刚刚下载完之后拖进插件文件夹就可以了。 感谢感谢❤️
