### ISSUE TITLE
Feature Request: 网页翻译

### ISSUE THREAD

**Issue by hujie12306** [Quorafind/Obsidian-Surfing#26]
### Feature Requested

It would be great if there is a web page translation function

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/61086637/203286202-e752a95b-a154-4488-bd7c-ef9a5834d836.png)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by windily-cloud** [comment]
这个用外部的词典比如欧陆词典就好了吧，或者在浏览器里打开，一个插件没必要搞得那么复杂。
