### ISSUE TITLE
[功能请求] 添加插件选项, 允许设置功能键更改打开链接行为

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Obsidian-Surfing#27]
### Feature Requested
目前, 直接点击链接是在ob里打开新标签页. 建议增加更多配合功能键的新行为. 例如, 允许用户使用alt+click在ob外的浏览器里打开页面, 使用ctrl+click在ob里的相邻窗格内打开页面, ctrl+shift+click在悬浮页内打开页面(配合hover editor), ctrl+alt+click在新的ob窗口里打开页面.
如此一来, 即可吸收如下设置.
![image](https://user-images.githubusercontent.com/65625632/203294104-1a68de9a-7576-48e5-8047-2dae25722297.png)

感谢费心开发, 一直在等原作者更新, 偶然看到cuman视频推荐, 立马就过来了. 顺便问下, cuman说有意向支持油猴插件, 如能实现那可太强了, 看B站视频进行学习并笔记, 没有油猴插件体验真的差强人意.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by windily-cloud** [comment]
#29
