### ISSUE TITLE
增加按alt键用浏览器打开

### ISSUE THREAD

**Issue by TheGodOfKing** [Quorafind/Obsidian-Surfing#29]
### Feature Requested

能加个按alt键（或者用户自定义）用浏览器打开么，有些网页还是想浏览器打开
![image](https://user-images.githubusercontent.com/32014745/203339252-93526abe-aed0-469d-a15e-0fbf100c9cae.png)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by windily-cloud** [comment]
这个功能本来有的，但考虑到后续ob会改api，就没添加这个功能。等到ob白板发布后应该就有了

**Comment by TheGodOfKing** [comment]
@windily-cloud 好等你开发
![99EFBAAE24B4B63C3DA23036FB4F12F9](https://user-images.githubusercontent.com/32014745/203927769-b03ac82c-9419-4905-8a63-8e0e0a788179.gif)
