### ISSUE TITLE
Feature Request: 建议插件改名, obsidian browser 或者 surf in obsidian 之类的

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Obsidian-Surfing#33]
### Feature Requested

感谢集成了text fragment功能, 体验很好, 省去了调用浏览器插件的流程.
既然已经有了自己的特色功能, 那么我想有一个更独立的名字或许更好.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
修改成了 Surfing
