### ISSUE TITLE
[Bug]: Mac设备下"复制指向突出显示的链接"开启后无效

### ISSUE THREAD

**Issue by AaronNick** [Quorafind/Obsidian-Surfing#46]
### Bug Description

Mac下，网页的右键菜单只有复制
- 已尝试重启obsidian
- 已尝试重装该插件
- 其余web-browser插件已关闭

网页选中后右键如下图：
![image](https://user-images.githubusercontent.com/46479652/204072942-6e124bdb-3949-4472-8b36-b8d816a5119e.png)

### Obsidian Version

0.3.0

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
目前不清楚该如何修复，已经用 mac 尝试了一下

**Comment by AaronNick** [comment]
尝试了下似乎还是无效，并不能拖动内容到新的面板：
> 按住 CTRL 拖动这个选中内容来生成链接

obsidian 版本：v1.0.3
surfing 版本：0.6.2

已尝试重启软件和插件，并测试了多个网页，也许是 obsidian 版本的原因？

**Comment by Quorafind** [comment]
这里指的是拖动到编辑器中，你这边需要拖到编辑器再尝试一下。

**Comment by AaronNick** [comment]
是的，我就是这么尝试的，左边网页，右边测试的md文件（编辑状态），按照你的提示，按住 Ctrl 无法拖动选中的内容到右边编辑器中。

另，按住 Ctrl 尝试拖动选中内容时，会出现一个和右键一样的 `copy` 菜单，但仍旧无法拖动选中的文字。

**Comment by AaronNick** [comment]
可以说勉强能够使用 😂
