### ISSUE TITLE
[Bug]: B站的复制时间戳没有分p

### ISSUE THREAD

**Issue by w0330t** [Quorafind/Obsidian-Surfing#53]
### Bug Description

在B站，点右键有个复制时间戳的选项。
该选项复制出来的链接没有分P导致实际视频地址错误。

### To Reproduce
1、打开这个[地址](https://www.bilibili.com/video/BV1ys411472E?p=7)。
2、右键点击”复制视频时间戳“并粘贴出来。[00m25s](https://www.bilibili.com/video/BV1ys411472E?t=00m25s)
3、打开粘贴的链接，视频变成了[这个](https://www.bilibili.com/video/BV1ys411472E)

PS：上面的链接没有问题，我不太懂gayhub为啥跳到B站会显示404，直接访问该链接没有问题。
### Obsidian Version

0.3.0

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by XMB-7** [comment]
我试了一下, 我这边没有问题, 在第十分钟截取时间戳, 生成正常链接如下, `https://www.bilibili.com/video/BV1ys411472E?t=600&p=7`, 你重启或者重装插件试试.

**Comment by w0330t** [comment]
我重新建立了一个新的资料库，然后手动仅添加了这个插件，测试了一下，问题依旧。
我仅把obsidian-surfing-0.3.0.zip解压缩然后把文件夹扔进了plugins目录。什么配置都没有修改。
然后建立了一个文档，做了个链接，点开。
复制出来的链接还是不带P。
[未命名.md](https://github.com/Quorafind/Obsidian-Surfing/files/10100399/default.md)

**Comment by XMB-7** [comment]
我知道了...我刚刚注意到我一直用的是B站右键自带的时间戳功能, 没用插件所提供的功能, 确实是有bug.

**Comment by Quorafind** [comment]
已经修复
