### ISSUE TITLE
[Bug]: URI Scheme `obsidian://web-open` not working

### ISSUE THREAD

**Issue by chrisgrieser** [Quorafind/Obsidian-Surfing#60]
### Bug Description

The `obsidian://web-open` does not seem to work for me. I tried encoded and non-encoded URLs.

### Relevant Screenshot

console output after trying:
<img width="1511" alt="Pasted image 2022-11-28 11 56 33" src="https://user-images.githubusercontent.com/73286100/204261404-f939356c-fa4a-40b1-aaf1-45695594eb9e.png">

### To Reproduce

Try to open any of these URIs:
```
obsidian://web-open?url=https://github.com/Quorafind/Obsidian-Surfing
obsidian://web-open?url=https%3A%2F%2Fgithub.com%2FQuorafind%2FObsidian-Surfing
```

### Obsidian Version

Obsidian 1.0.4

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
I just checked, the bookmarklet, too, does not work.

**Comment by Quorafind** [comment]
which os are you using? Seems like a bug related to MacOS

**Comment by Quorafind** [comment]
I tried URL scheme with my mac, and it works as normal.. it is weird now, I will check it again.

**Comment by chrisgrieser** [comment]
using macOS 13.0.1 (M1)

**Comment by chrisgrieser** [comment]
weird, just updated to 0.4.0, and the problem still persists.

**Comment by Quorafind** [comment]
if this issue remains in 0.8.4 ?
