### ISSUE TITLE
[Bug]: 导致“Buttons”创建的link类型的按钮无效

### ISSUE THREAD

**Issue by shuojie819** [Quorafind/Obsidian-Surfing#61]
### Bug Description

更新到最新的Surfing(0.4.0)会导致由“Buttons”创建按钮失效

### Relevant Screenshot

> 比如示例库中的四个按键全部失效；

![image](https://user-images.githubusercontent.com/72399630/204345799-5b8bdabc-7130-456d-8b22-f9351de6e24d.png)

### Obsidian Version

1.0.3

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
你希望这四个是能在 surfing 中打开，还是说在外部网站中打开

**Comment by shuojie819** [comment]
如果可以的话，我可以选择先打开吗？
直接点击可以在库内打开，加辅助键可以在库外打开。如果不可以的话，我感觉在库外打开的话会好一点（个人观点）。

**Comment by Quorafind** [comment]
问题在于无法监控 window.open 的辅助键。。

**Comment by shuojie819** [comment]
哦哦，这个不太懂，这个主要是可以打开就可以了。无论是库内还是库外。

**Comment by Quorafind** [comment]
修复了
