### ISSUE TITLE
Feature Request: 使用“LinkCard”会导致Surfing失效

### ISSUE THREAD

**Issue by shuojie819** [Quorafind/Obsidian-Surfing#62]
### Feature Requested

使用LinkCard渲染的链接，无法使用Surfing在内部打开，希望可以适配一下。

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/72399630/204347992-847f824d-f32f-4172-8994-57f77dbe00ac.png)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
因为 Linkcard 采用的是 window.open 功能，我这边无意去监控所有的 window.open ，因为这个极有可能会将所有的打开都给覆盖掉

**Comment by shuojie819** [comment]
好的😊
