### ISSUE TITLE
[Bug]: bilibili视频复制时间戳无效

### ISSUE THREAD

**Issue by zangyd** [Quorafind/Obsidian-Surfing#66]
### Bug Description

bilibili视频的复制时间戳功能，不起作用。点击复制后，粘贴板里面没有数据

### Obsidian Version

1.0.3

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
请提供你失败的 bilibili 时间戳样例
