### ISSUE TITLE
Feature Request: 支持图床管理html文件

### ISSUE THREAD

**Issue by Tony-zf1** [Quorafind/Obsidian-Surfing#67]
### Feature Requested

Bon佬和皮皮佬好，我有个使用markmind批注图床pdf的工作流，用起来比较方便，不知道用来这个插件上管理html批注是否也容易实现，在此介绍供参考。

在和markmind作者几次反馈后，markmind现在支持在pdf附件的多种管理功能：
- **在线pdf**：可以将pdf附件放到图床中，像图片一样管理，只需要同步md也可以保证批注链接不失效
- **pdf id**: 使用id来指向存放批注信息的md，这个md中另有pdf链接的信息，这样更新pdf路径可以保证回链不失效
- **缓存pdf**: pdf文件可能比较大，每次预览会消耗大量流量，markmind在打开链接时，会先到附件文件夹匹配对应的PDF，匹配成功后使用本地pdf打开，如果不成功就打开原始的图床链接预览，然后保存一份缓存到附件文件夹，这样可以大大减少流量消耗。
![image](https://user-images.githubusercontent.com/79450935/204449359-3d0ffc21-26c5-48f7-930d-c156866be5b5.png)

目前我试了一下，html放到图床之后，用Surfing打开会自动触发下载，如果能够做到预览而不是下载，那么参照上述pdf的流程也可以对html实现稳定的批注回链了！

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Tony-zf1** [comment]
现在发现[Annotator](https://github.com/elias-sundqvist/obsidian-annotator)插件可以预览图床的html，而不会触发下载，也许可以借鉴一下。这样只要也实现缓存html附件解决流量消耗问题就可以了
![image](https://user-images.githubusercontent.com/79450935/204455170-1363fc20-4136-4518-add3-3f415ef0180a.png)

**Comment by Quorafind** [comment]
是否有图床的 HTML 的链接示例

**Comment by Tony-zf1** [comment]
替代方案： 可以使用github托管静态html，用surfing访问托管后的github链接，[参考链接](https://juejin.cn/post/7092921196911525919)
