### ISSUE TITLE
[Bug]: 标签页的图标异常拉伸

### ISSUE THREAD

**Issue by Yaozhuwa** [Quorafind/Obsidian-Surfing#68]
### Bug Description

标签页的图标被异常拉伸了。

### Relevant Screenshot

<img width="754" alt="image" src="https://user-images.githubusercontent.com/28787183/204479353-c980b5ab-ae39-43e0-b904-082ec13da3a1.png">

### To Reproduce

1. 新建标签页
2. 随便输入网址，例如 www.baidu.com
3. 看标签页的图标

### Obsidian Version

1.0.3

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/204488595-e1a3fed9-eeea-4d89-85d7-420a98684152.png)

无法复现，请查看是否是主题或者其它插件影响

**Comment by Yaozhuwa** [comment]
我筛查了一下，是一个CSS影响了图片的显示，非常抱歉。
