### ISSUE TITLE
[Bug]: 不能正常的运行了

### ISSUE THREAD

**Issue by shuojie819** [Quorafind/Obsidian-Surfing#71]
### Bug Description

无法在OB正常打开网页（最新版0.4.4）

### Relevant Screenshot

![surfing-BUG](https://user-images.githubusercontent.com/72399630/204534028-014b1537-c596-4513-b9c5-031a89eae1a3.gif)

### Obsidian Version

1.0.3

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
#72
