### ISSUE TITLE
[Bug]: 跳转到已打开页面, 实际不会进行跳转, 而且内容高亮也出问题

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Obsidian-Surfing#76]
### Bug Description

关联#48

比如在A页面截取两段内容, 复制各自链接(link1&link2)到B页面. 关闭A页面, 在B页面先点击link1, 将会正常打开并切换到A页面, 然后保持A页面开启回到B页面再点击link2, 此时则不会如预期般再跳回A页面, 并且即便进行手动切换, 也不再显示内容高亮. 

重复试验一次, 在A页面截取两段内容, 复制各自链接(link1&link2)到B页面. 关闭A页面, 这回选择在B页面直接点击link2, 则会跳转到A页面但不显示高亮内容, 此时再回到B页面点击link1, 惊讶发现不仅不跳转而且不高亮. 此时手动跳转到A页面并将之关闭, 再回到B页面点击link1, 此时link1又能正常跳转并高亮了.

### Obsidian Version

0.15.8

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
第一个场景无法复现

**Comment by XMB-7** [comment]
我又试了一下, 不跳转是复现了, 但不高亮没复现出来. 这回两个链接都能正确高亮文本, 就是需要手动切换标签页.
![Obsidian_Xxz8fhEX44](https://user-images.githubusercontent.com/65625632/204810830-3ed83e17-5255-4638-9e3e-b2c626c3be30.gif)

**Comment by XMB-7** [comment]
我又试了一下, 不跳转是复现了, 但不高亮没复现出来. 这回两个链接都能正确高亮文本, 就是需要手动切换标签页.
![Obsidian_Xxz8fhEX44](https://user-images.githubusercontent.com/65625632/204810830-3ed83e17-5255-4638-9e3e-b2c626c3be30.gif)

**Comment by XMB-7** [comment]
感谢大佬, 效率是真滴高 💕
