### ISSUE TITLE
Feature Request: 自动将url对中文的编码反转

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Obsidian-Surfing#77]
### Feature Requested

![image](https://user-images.githubusercontent.com/65625632/204718309-5314c2d1-d46d-4afd-9c46-41cb57a0999a.png)
图上这俩是一个链接, 都能进行跳转并高亮, 但后者的可读性明显更高.
这是通过quickadd实现的, 希望能够将其吸收进插件中, 增添一个插件选项让用户选择是否启用这一功能. 具体也不是很懂, 直接用的大佬给出的解决方案, 或许对某些特殊字符需要特殊处理. 但我个人总是直接对text=之后的部分进行反转, 无论中文还是英文, 似乎也没遇到过什么问题, 哪怕英文单词间包含空格.

```js quickadd
selObj = window.getSelection();
text = selObj.toString();
//await this.quickAddApi.utility.getClipboard();
text = await decodeURIComponent(text)
this.quickAddApi.utility.setClipboard(text);
//console.log("main " + text);
return text;
```

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
这个选项会带来不稳定性，参考复制的时候如果附带了 `[` 或者 `)` 或者其它的符号的时候，而且在复制的时候加太多判断以及运算也会很麻烦，我将你的这个脚本加到 readme 中让用户自己选择使用
