### ISSUE TITLE
Feature Request: 优化插件设置选项及相关命令的名字

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Obsidian-Surfing#80]
### Feature Requested

建议将"在同一标签页里打开网页"修改为"在同一窗格里打开新的网页".
"在同一标签页里打开网页", 很容易让人误以为说的是在当前标签页里用新页面来覆盖旧页面(比如在A页面上打开a链接, A页面上的原有内容将被覆盖). 
毕竟对于ob1.0, 所谓标签页就是笔记页. 而官方对同一个ob窗口内的上下左右分页面的叫法似乎是窗格(pane). 或是直接用页面替换窗格, 也都比目前的标签页指向得更准确.
类似地, 将相关命令名字改为“Surfing: 切换是否在同一窗格里打开新的网页”.
![image](https://user-images.githubusercontent.com/65625632/204970283-82d3d98b-6819-4eea-ae9f-ce6d313d0f3e.png)
![image](https://user-images.githubusercontent.com/65625632/204970456-3cd7b2a7-fadb-48f9-8e65-36c55ef58e80.png)

此外还可以将"在当前页面标题栏中搜索"改为"在当前标签页中唤出网址搜索栏".

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
@windily-cloud 你这边可以看一下合不合理吗？

**Comment by windily-cloud** [comment]
我觉得这就是个习惯的问题，毕竟就只是个名字，具体功能描述看看文档和试试就知道了。分歧在于是否沿用浏览器中的命名习惯还是沿用ob的命名习惯。

`Tab`是浏览器的命名习惯，`Pane`是ob的命名习惯。但你这个“窗格”在计算机里我是听都没听过，翻译成“面板”可能更好。要我说还是沿用浏览器的风格比较好，包括之前那个`复制指向突出显示的链接`，也是浏览器的风格，这是大多数人熟悉的（至少在edge和chrome中是这样的）。

所以我的意见是懒得改，习惯问题那就少数服从多数，浏览器的风格想必是绝大多数人能接受的，就这样。

**Comment by XMB-7** [comment]
我觉得你可能误解了我的意思, 这跟命名习惯没有关系, 抛开pane不谈, 当前的描述是在当前tab里显示新的内容, 但插件的实际行为却是打开新的tab显示新的内容, 这是有明确的语义冲突的. 
虽然不改也行, 试一遍就能试出来实际功能是啥, 但我确实觉得优化比不优化要好.

**Comment by XMB-7** [comment]
> 因为当你有一个split的tab，不会创建新的split

我是不用split的, 我是用新tab打开转用hover editor变为悬浮窗...
难道用split是open in same tab吗, 我试一下, 反正不用split是open in new tab

**Comment by XMB-7** [comment]
发现问题了: 用了split时候, 实际行为是open in same tab, 比如点击5个链接, 只会产生1个tab; 不用split时候, 实际行为是open in new tab, 比如点击5个链接, 将会产生5个tab. 我是不用split的, 所以咱俩体验不一样, 怪不得有驴唇不对马嘴之感...
不确定这是bug还是故意这么设计的. 
所以现在是这样, 这一个选项实际上控制了两种行为, 是否进行split以及是否打开新tab, 但又只支持"split+不打开新tab"以及"不split+打开新tab". 
那我建议进行功能拆分, 完全支持是否split以及是否打开新tab两两组合的四种情况, 对应设置选项也拆成两个.
@Quorafind bon佬如果觉得有必要, 可以单开一个issue, 或者关闭这个issue, 维持现状也挺好的, 目前插件已经满足我的使用习惯(不进行split然后总是打开新tab的).

**Comment by XMB-7** [comment]
是的, 我最初的理解有误. 所以现在事情其实变简单了, 把设置选项改为"split right & open in same tab"即可, 一开二者皆开, 一否二者全否. 中文可以改为比如"向右分页 & 在同一标签页中打开网页".

**Comment by windily-cloud** [comment]
要我说，他们应该先看文档。

**Comment by XMB-7** [comment]
然而文档里写的是面板...
![image](https://user-images.githubusercontent.com/65625632/205052835-70ed2a15-da41-4ae9-af53-eab47b5b7303.png)

**Comment by windily-cloud** [comment]
理解了不就行了，此贴终结。

**Comment by windily-cloud** [comment]
可以，这些文档都是我之前随便写的，如果你能加入进来是再好不过的了，我巴不得用户去看源码，哈哈。bon佬的代码可读性也很高，就靠你了！
