### ISSUE TITLE
[Bug]: B站某些视频复制时间戳无效。

### ISSUE THREAD

**Issue by w0330t** [Quorafind/Obsidian-Surfing#85]
### Bug Description

问题和[#66](https://github.com/Quorafind/Obsidian-Surfing/issues/66)相同，点击后剪切板为空

### Relevant Screenshot

我大概看了一下，带P的复制没有问题，但如果不带P就不行。
[链接1](https://www.bilibili.com/video/BV1bx411M7Zx)

默认`p=1`的视频，在URL不写p参数的情况下依然是不能复制
[链接2](https://www.bilibili.com/video/BV1ys411472E)

当加上`p=1`参数后，该功能恢复正常。
[链接3](https://www.bilibili.com/video/BV1ys411472E?p=1)

即使没有分p的视频，加上`p=1`的参数，该功能依然正常。
[链接4](https://www.bilibili.com/video/BV1Ux411j7ri/?p=1)

### Obsidian Version

0.5.0

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
已修复。 #84
