### ISSUE TITLE
[Bug]: 打开外部连接时会自动打开内部连接

### ISSUE THREAD

**Issue by shuojie819** [Quorafind/Obsidian-Surfing#86]
### Bug Description

`Ctrl + Click`时，会同时在ob内部和外部打开连接

### Obsidian Version

1.0.3

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
请提供对应的会跳转到外部的链接样例，以及你使用的什么模式，所见即所得或者源码或者预览模式

**Comment by shuojie819** [comment]
使用阅读模式：
> 连接样式
![image](https://user-images.githubusercontent.com/72399630/205323549-cc43ab34-5b82-4826-9a28-a8c94fd8600e.png)

**Comment by shuojie819** [comment]
该问题已在0.6.1中解决
