### ISSUE TITLE
[Bug]: 不能打开本地html

### ISSUE THREAD

**Issue by Jasonhyliang** [Quorafind/Obsidian-Surfing#87]
### Bug Description

macos系统, 点击html文件没反应, html reader插件可以, 但冲突

### Obsidian Version

1.0.3

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
请问 0.7.0 是否还有同样的问题？

**Comment by Quorafind** [comment]
如果还有问题请重新打开这个 issue。
