### ISSUE TITLE
[Bug]: 点击外部链接跳转出两个页面

### ISSUE THREAD

**Issue by NNGTHB** [Quorafind/Obsidian-Surfing#88]
### Bug Description

在ob打开链接会出现两个一样的tabs

### Relevant Screenshot

![动画](https://user-images.githubusercontent.com/115760745/205590187-243bf333-42b0-4a48-9829-6f497ff18049.gif)

### Obsidian Version

v1.0.3

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Metadata 的链接是 frontmatter link 这个插件实现的是吗？

**Comment by NNGTHB** [comment]
![MH8$OB1XV_~T%KT _O0C02Y](https://user-images.githubusercontent.com/115760745/206675941-f6940e69-ff1e-4648-b153-3341bdd35e4f.png)
不是，我没有装这个插件
