### ISSUE TITLE
[Bug]:  Vivaldi浏览器用不了 bookmarklets code。

### ISSUE THREAD

**Issue by Connor-yang96** [Quorafind/Obsidian-Surfing#90]
### Bug Description

![image](https://user-images.githubusercontent.com/81000027/205931152-e0335bbd-ec80-4c97-975c-2f1e39408451.png)

弹出空白页。没有弹出ob

### To Reproduce

1. bookmarklet code 放在 Vivaldi 书签栏上方。
2. 打开任意网页
3. 点击 bookmarklet code 。
4. 打开空白页面，没有弹出ob。

在chrome，edge 的书签栏上，没有问题。

### Obsidian Version

1.0.0

### web-browser-only

- [x] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by windily-cloud** [comment]
这玩意儿应该是vivaldi浏览器的bug吧，edge，firefox和chrome都有，就他没有。

**Comment by Connor-yang96** [comment]
> 

解决了。从chrome导出 bookmarklets，成html文件，再导入vivaldi，就可以用啦
