### ISSUE TITLE
[FR] 只提取正文，其余的不要

### ISSUE THREAD

**Issue by Connor-yang96** [Quorafind/Obsidian-Surfing#93]
### Feature Requested

保存页面为md文件，可否只提取正文啊。保存整个页面，要删除很多多余的东西。

（ps：俺不知道 只提取正文，在代码上，是否需要适配各种不同的网页代码，不知是否耗时）

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by XMB-7** [comment]
这个需要逐网页做适配, 建议去用简悦(一款浏览器插件), 能够提取正文并且导入ob

**Comment by Connor-yang96** [comment]
> 

不在surfing里操作的，那算了。Close！

**Comment by Quorafind** [comment]
难度太大，而且我觉得如果有很多需要裁剪的网站，就过于麻烦了

**Comment by XMB-7** [comment]
@Quorafind 请问大佬有无计划支持一下浏览器的插件, [这里](https://github.com/Trikzon/obsidian-web-browser/issues/43#issuecomment-1315720717)有人提到在electron里面实现浏览器脚本似乎是可行的, 若能用上油猴脚本以及各种浏览器插件, 那ob的使用体验可就太顶了.
